### ISSUE TITLE
MIUI 8 上没法显示

### ISSUE THREAD

**Issue by zhanggao** [koudle/FloatingLayer#1]

**Comment by koudle** [comment]
目前手头上没有小米的手机，周一来看一下

**Comment by zhanggao** [comment]
@koudle 看过没？

**Comment by koudle** [comment]
不好意思，没有看啊。。。。。没找到手机

**Comment by zhanggao** [comment]
跳到下一个Activity就没了。
如果跳下一个后执行以下三句代码就会重新显示出来。
mLayoutParams.token = token;
mWindowManager.removeView(mPopView);
mWindowManager.addView(mPopView, mLayoutParams);

**Comment by koudle** [comment]
这是因为由于没有申请权限，所以要想在WindowManager里添加view并显示的话，就需要token的值（系统悬浮窗权限这里的token为null就可以显示），这里token在Activity里通过getWindow().getDecorView().getWindowToken()来取，其实我这里最重要的问题就是解决如何取这个token的问题。

**Comment by iikk** [comment]
FloatingLayer.getInstance(MyApplication.this).show(activity);这句话放在MyApplication里就是在启动每个activity的时候都show一次，原本这样的窗口只在某一个activity里显示的，这样理解对吗？如果我的应用内悬浮窗是在某个条件下触发再显示，在有些情况下又需要去掉（比如视频悬浮窗，在应用外不显示，=-=产品要求的），用你这个方便吗，还有，每打开一个activity是不是要新建播放器，多个播放器会不会同时在播放

**Comment by koudle** [comment]
视频浮窗应该实现不了，虽然浮窗view其实是一个view，所以不会有多实例的view，但是原理其实是当打开一个新的actvivity时，把浮窗remove掉，然后在add到新的activity上面，所以会有突然消失在出现的问题，体验应该不好

**Comment by iikk** [comment]
好的，谢谢。祝周末愉快^^
